name: lint
on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/go-lint.yaml"
      - "helpers/foundation-deployer/**"
permissions:
  contents: read

concurrency:
  group: '$${{ github.workflow }}-$${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: [helpers/foundation-deployer]
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: ${{ matrix.folder }}/go.mod
          cache-dependency-path: ${{ matrix.folder }}/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: latest
          working-directory: ${{ matrix.folder }}
          args: --timeout=5m
