name: go-test

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - 'helpers/foundation-deployer/**'
      - '.github/workflows/go-test.yaml'

permissions:
  contents: read

concurrency:
  group: '${{github.workflow}}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  go-test:
    name: go-test
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        folder: [helpers/foundation-deployer]
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version-file: ${{ matrix.folder }}/go.mod
        cache-dependency-path: ${{ matrix.folder }}/go.sum
    - run: |-
        go test ./... -v
      shell: bash
      working-directory: ${{ matrix.folder }}
      
